services:
  - type: web
    name: cinevault-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      # You will need to manually add your secrets (like MONGO_URI) in the Render Dashboard
